---
fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: ["--fix", "lf"]
      - id: check-json
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
      - id: check-symlinks
  - repo: https://github.com/toddnguyen47/pre-commit-hooks
    rev: v1.6.0
    hooks:
      - id: prettify-json
        args: ["--indent", "2"] # defaults to indenting with 2 spaces
        types: ["json"]
      - id: convert-beginning-spaces
        # --tab-size defaults to 4 with no args
        # --comment-char is empty string ("") by default
        args: ["--tab-size", "4", "--comment-char", "*"]
        types: ["java"]
